import { Inter } from 'next/font/google';
import '../styles/globals.css';
import Footer from '@/components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Starting Template Next JS',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="page__wrapper">
          <main className="main">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
