import { getDictionary } from './dictionaries';

export const metadata = {
  title: 'Starting Template Next | Home',
  description: 'Generated by create next app',
};

export default async function Home({ params }) {
  const { locale } = params;

  const dict = await getDictionary(locale);

  return (
    <div className="container">
      <h1>{dict.homePage.title}</h1>
    </div>
  );
}
