import Image from 'next/image';
import imageAbout from '@/public/images/about.png';

import { getDictionary } from '../dictionaries';

import clsx from 'clsx';
import s from './about.module.scss';

export const metadata = {
  title: 'Starting Template Next | About',
  description: 'Generated by create next app',
};

const AboutPage = async ({ params }) => {
  const { locale } = params;

  const dict = await getDictionary(locale);

  return (
    <article className={clsx('container', s.wrapper)}>
      <Image src={imageAbout} alt="about" width={300} height={'auto'} />
      <h1>{dict.aboutPage.title}</h1>
      <p className={s.text}>{dict.aboutPage.desc}</p>
    </article>
  );
};

export default AboutPage;
